### ISSUE TITLE
Got some erro while connecting.

### ISSUE THREAD

**Issue by GabeHuhn** [tschartz/pyrp360#1]
Information:
OS: ubuntu 18.04

Installed python3 from ubuntu's repository.
Installed pip for python3.
Ran pip3 to install libs. (PyGOBject and PySerial)
Ran pyrp360.py with the following command - python3 pyrp360.py

The program runs and find my device.
After clicking on connect, it reads my presets, but it get stuck on 80%.
I get the following error on terminal.

`Received: b'U\x00\x01\xf4\x00B\x00\xc9\x03@["rcr",201,202,{"preset":{"name":"Clean Funk","PRS LEVL":99,"FACTMODIFY":2,"fxc":{"0":{"ENABLE":0,"fx":{"name":"wah.CLYDEWAH","WAH LEVL":6,"PEDAL":99}},"1":{"ENABLE":0,"fx":{"name":"cmpr.DIGICOMP","LEVEL":66,"SUSTAIN":23,"TONE":50,"ATTACK":0}},"2":{"ENABLE":0,"fx":{"name":"dist.DS DIST","DIST":99,"TONE":99,"LEVEL":99}},"3":{"ENABLE":1,"fx":{"name":"amp.68 PLEXI","CABINET":11,"GAIN":30,"LEVEL":60,"BASS":90,"MID":50,"TREBLE":30}},"4":{"name":"eq.EQ","ENABLE":0,"LOW LEVL":12,"LOW FREQ":9,"LOW'
Sending: UrBD
Received: b'U\x00\x01\xf4\x00B\x00\xca\x03@ BW":1,"MID LEVL":14,"MID FREQ":34,"MID BW":1,"HIGHLEVL":16,"HIGHFREQ":14,"HIGH BW":1},"5":{"ENABLE":0,"fx":{"name":"gate.GATE","THRESHLD":40,"ATTEN":99,"ATTACK":0,"RELEASE":0}},"6":{"name":"vol.VOLUME","VOLUME":99},"7":{"ENABLE":0,"fx":{"name":"mod.EH PHASR","RATE":25,"COLOR":1}},"8":{"ENABLE":0,"fx":{"name":"dly.ANALOG","TIME":340,"REPEATS":25,"DLY LEVL":35,"TAP DIV":3}},"9":{"ENABLE":0,"fx":{"name":"rvb.LEXAMBNC","RVB LEVL":49,"PREDELAY":2,"DECAY":30,"LIVENESS":40}}},"ctrls":{"treadle":'
Sending: UsBC
Received: b'U\x00\x01\x14\x00B\x00\xcb\x03@{"LNK":"../../fxc/6/VOLUME","MIN":0,"MAX":99},"altTreadle":{"LNK":"../../fxc/0/fx/PEDAL","MIN":0,"MAX":99},"lfo1":{},"ctrlVSw":{"LNK":"../../fxc/0/ENABLE"},"ctrlA":{"LNK":"../../fxc/2/ENABLE"},"ctrlB":{"LNK":"../../fxc/8/ENABLE"},"ctrlC":{"LNK":"../../fxc/9/ENABLE"}}}}]'
Current preset: {"name":"Clean Funk","PRS LEVL":99,"FACTMODIFY":2,"fxc":{"0":{"ENABLE":0,"fx":{"name":"wah.CLYDEWAH","WAH LEVL":6,"PEDAL":99}},"1":{"ENABLE":0,"fx":{"name":"cmpr.DIGICOMP","LEVEL":66,"SUSTAIN":23,"TONE":50,"ATTACK":0}},"2":{"ENABLE":0,"fx":{"name":"dist.DS DIST","DIST":99,"TONE":99,"LEVEL":99}},"3":{"ENABLE":1,"fx":{"name":"amp.68 PLEXI","CABINET":11,"GAIN":30,"LEVEL":60,"BASS":90,"MID":50,"TREBLE":30}},"4":{"name":"eq.EQ","ENABLE":0,"LOW LEVL":12,"LOW FREQ":9,"LOWUB@ BW":1,"MID LEVL":14,"MID FREQ":34,"MID BW":1,"HIGHLEVL":16,"HIGHFREQ":14,"HIGH BW":1},"5":{"ENABLE":0,"fx":{"name":"gate.GATE","THRESHLD":40,"ATTEN":99,"ATTACK":0,"RELEASE":0}},"6":{"name":"vol.VOLUME","VOLUME":99},"7":{"ENABLE":0,"fx":{"name":"mod.EH PHASR","RATE":25,"COLOR":1}},"8":{"ENABLE":0,"fx":{"name":"dly.ANALOG","TIME":340,"REPEATS":25,"DLY LEVL":35,"TAP DIV":3}},"9":{"ENABLE":0,"fx":{"name":"rvb.LEXAMBNC","RVB LEVL":49,"PREDELAY":2,"DECAY":30,"LIVENESS":40}}},"ctrls":{"treadle":UB@{"LNK":"../../fxc/6/VOLUME","MIN":0,"MAX":99},"altTreadle":{"LNK":"../../fxc/0/fx/PEDAL","MIN":0,"MAX":99},"lfo1":{},"ctrlVSw":{"LNK":"../../fxc/0/ENABLE"},"ctrlA":{"LNK":"../../fxc/2/ENABLE"},"ctrlB":{"LNK":"../../fxc/8/ENABLE"},"ctrlC":{"LNK":"../../fxc/9/ENABLE"}}}

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "pyrp360.py", line 287, in load_banks
    self.preset.load_from_device(self.device.get_active_preset())
  File "/home/gabriel/Área de Trabalho/pyrp360-master/preset.py", line 38, in load_from_device
    self.get_data(data)
  File "/home/gabriel/Área de Trabalho/pyrp360-master/preset.py", line 49, in get_data
    self.data = json.loads(data)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 967 (char 966)
`
Am I doing everything properly?
Thanks for your time.

**Comment by tschartz** [comment]
Hi,
You did everything properly.
There was an error after reading the preset 'clean funk'. 
It happens sometimes with certain presets. I will fix this soon.

**Comment by tschartz** [comment]
Hi,
I uploaded a fix for this issue.
