### ISSUE TITLE
Questions on usage

### ISSUE THREAD

**Issue by danilo-bc** [tschartz/pyrp360#2]
I was pleasantly surprised when I found this repository, thank you very much for the work!

I just tried it without connecting my device with
```
python pyrp360.py
```

and received

```bash
(pyrp360.py:18231): Gtk-WARNING **: 20:06:48.211: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(pyrp360.py:18231): Gtk-WARNING **: 20:06:48.211: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
Traceback (most recent call last):
  File "/home/user/Documents/pyrp360/pyrp360.py", line 308, in <module>
    rp360 = RP360()
            ^^^^^^^
  File "/home/user/Documents/pyrp360/pyrp360.py", line 122, in __init__
    if self.device.detect_device():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Documents/pyrp360/device.py", line 38, in detect_device
    self.logger.critical("No device detected in ", ports)
  File "/usr/lib64/python3.11/logging/__init__.py", line 1536, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib64/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/lib64/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/home/user/Documents/pyrp360/pyrp360.py", line 38, in handle
    print(record.getMessage())
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
```
The line "No device detected in ports" suggests that the program only works with the device plugged in. I'll find a cable and try again, but I suggest making the program exit more gracefully. Maybe a try-catch statement to instruct the user to check if the device has been properly inserted?

Also, can you provide information on how you built the application? Maybe someone can make a terminal port with the fundamentals of how it works.

Once again, thank you for your work, even if the repository has not been updated in a while!

**Comment by tschartz** [comment]
Hi,
Yes, the program looks for a connected device at startup, it won't work without it.
I made this mainly for my own needs so I didn't look into other possible use cases.

I'll try to add a fix for this issue as soon as I can. 

I will also add more info on how the program works as you suggested.

Thanks for reporting this issue.

**Comment by danilo-bc** [comment]
Thank you. Since Nexus software is only available via internet archive links, and nothing available on Linux, your work is very valuable to keep this awesome multi fx usable.

**Comment by tschartz** [comment]
Hi,
I commited a fix for the startup issue and added an explanation on how the program works in the wiki section.
