### ISSUE TITLE
List of supported devices and USB IDs

### ISSUE THREAD

**Issue by ndim** [tschartz/pyrp360#4]
I am looking to write a udev rules file to contribute to pyrp360.

My RP360 (no XP) has idVendor 1210 and idProduct 0032.

```
# Digitech RP360 Guitar Multi-Effect Floor Processor with USB Streaming
ACTION=="add", SUBSYSTEM=="tty", ATTRS{idVendor}=="1210", ATTRS{idProduct}=="0032", TAG+="uaccess"
```

Could someone with a RP360 XP run `lsusb | grep DigiTech` and see what shows up?

**Comment by tschartz** [comment]
Hi, my XP has the same : idVendor 1210 and idProduct 0032

**Comment by ndim** [comment]
FTR, I have also submitted that USB ID to the USB ID repository. See https://usb-ids.gowdy.us/read/UD/1210 for progress.
